### ISSUE TITLE
Only compiles on OS X Mountain Lion (10.8)

### ISSUE THREAD

**Issue by pkluz** [sinoru/STwitter#1]
Accounts and Social Framework are only available on the Mountain Lion release of Xcode. Precompiler flag `__MAC_10_8` obviously not recognized as well.

Whilst deployment might work on <10.8 it might be a good idea to add ML as a requirement for building the Framework?

**Comment by sinoru** [comment]
Ok. I understand it. I will make a branch for Xcode 4.3.
